:doctype: book
:imagesdir: ./images
:iconsdir: ./icons
:nofooter:


= Hsiang-Jui (Jerry) Lin

[#academic-record]
=== Academic Record
'''
[horizontal]
2012-2016:: _National Taiwan University, Bachelor of Computer Science and Information Engineering_ +
Undergraduate thesis: _Solving graph domination problem on DH graph using split decomposition_
2017-2021:: _National Taiwan University, Master of Computer Science and Information Engineering_ +
Teaching assistant of _System Programming_ course (2016-2017)
2021-:: _National Taiwan University, Doctor of Computer Science and Information Engineering_

[#work-experience]
=== Work Experience
'''
[horizontal]
2010 - 2016:: **Software Developer at CAVEDU Education (CAVEDU 教育團隊)** +
Developer of AppInventor project, Authored LeJOS on LEGO NXT book.

2018 Jun. - 2019 Jun.:: **R&D Assistant at Microsoft Taiwan** +
Bing's Reverse Geocoder backend development

2021 Sep. - 2022 Sep.:: **R&D Assistant at ADLINK Technology Inc.** +
Develop distributed consensus and traffic control using Zenoh

[#projects-and-publications]
=== Publications

[#lejos-book]
(2013) _機器人程式設計與實作：使用 Java_ / _Robotic Programming Design and Practices: Using Java_:: A book introduces leJOS framework on LEGO NXT robots. +
ISBN: link:http://isbn.ncl.edu.tw/NCL_ISBNNet/main_DisplayRecord.php?PHPSESSID=c8kchinqo5ncq873i47c4sqkb0&Pact=Display&Pstart=1[9789862768228]

[#undergraduate-thesis]
(2016) Undergraduate thesis: _Solving graph domination problem on DH graph using split decomposition_:: The study focuses on total and paired domination problems on distance-hereditary graph. Discovered an alternative optimal solution to total domination based on split decomposition. The handout can be found in the link:https://drive.google.com/file/d/18H1fvSZ7td3vArSJaeoTKkLjJ-DqApaP/view?usp=sharing[link].

[#master-thesis]
(2021) Master thesis: _Occlusion resistant tracking based on idempotent adjunction relationship between cyber and physical objects_::
This work combines deep learning and formal methods to tackle the occlusion in image tracking-by-detection problem. It developed a method to establish strong relationship among sensor data and learned representations, and achived short-term prediction of vehicle movements based on the material derivative method. The model is trained on completely labeled data is evaluated on partially occluded data. It shows 0.3 meter displacement error in average.

[#rtsca22]
(RTSCA 2022) _Scalable and Bounded-time Decisions on Edge Device Network using Eclipse Zenoh_::
This work developed an collaborate decision algorithm based on the _cheap consensus_ concept. By stacking CRDT, Reliable Broadcast and the data exchange framework _Zenoh_ together, the method was able to achieve consistenct decision among several peers within a bounded period of time. It also evaluated the performance on Zenoh and CycloneDDS.

=== Participated Projects

[#torfs]
TorFS (2019)::
 The project exploited free storage by abusing Tor's Onion service. It provided a virtual file system that stored data blocks as RSA public keys in disguise, and distributed them to the rest of Onoin network. (link:https://github.com/jerry73204/cns-final-tor-store[github])

par-stream (2020)::
It developed building blocks for asynchronous parallel data flow for Rust. It was develped to serve image data processing that mix heavy I/O and computation tasks. It provided iterator-style stream combinators to distribute data and scale on workers, and is designed to support Rust's async/await in nature. (link:https://github.com/jerry73204/par-stream[github])

NEWSLAB Autonomous Vehicle Group (2019-)::
The lab project develops a complete data processing system for traffic scenes. The tasks convered data collection, equipment design, data processing pipeline and data analysis. The vision is to provide a data processing pipeline to generate high precision data from LiDAR to aid the performance of camera based models. The project information can be found in the link:https://newslabntu.github.io/DanielFolio/projects/3_project/[lab page].

=== Research Interests

One recent reserach is to establish verifiable properties on learend scene detection. In the recent thesis _Occlusion resistant tracking based on idempotent adjunction relationship between cyber and physical objects_, it provides a framework to guarantee strong equivalence from detection and raw sensor data, which idea was inspired from category theory. The future work is to characterize the scene objects in more constructive manner, maybe using developed methods from differential geometry, and combine it with modern machine learning constructs.

Another research interest is developing distributed decisions on unreliable systems. The recent project with ADLINK Inc. developed distributed decision on vehicles, that aims to be efficient and support dynamic memberships. In the project, we provided a decision model based upon CRDT with consistency guarantees, and implemented a baseline consensus algorithm based on BFT.
